name: NVIDIA PyTorch Job

on:
  workflow_dispatch:
    inputs:
      script_content:
        description: 'Content of Python script'
        required: true
        type: string
      filename:
        description: 'Name of Python script'
        required: true
        type: string

jobs:
  train:
    runs-on: [gpumode-nvidia-arc]
    container:
      image: nvidia/cuda:12.4.0-devel-ubuntu22.04
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create script
      shell: python
      run: |
        with open('${{ github.event.inputs.filename }}', 'w') as f:
            f.write('''${{ github.event.inputs.script_content }}''')

    - name: Install dependencies
      run: |
        if grep -rE "(import numpy|from numpy)" "${{ github.event.inputs.filename }}"; then
          echo "Numpy detected, installing numpy"
          pip install numpy
        fi
        # Check if 'import torch' is in any Python file
        if grep -rE "(import torch|from torch)" "${{ github.event.inputs.filename }}"; then
          echo "PyTorch detected, installing torch"
          pip install torch
        fi
        # Check if 'import triton' is in any Python file
        if grep -rE "(import triton|from triton)" "${{ github.event.inputs.filename }}"; then
          echo "Triton detected, installing triton"
          pip install triton
        fi

    - name: Run script with NSight Compute profiling
      run: |
        # First run normally and capture output
        python "${{ github.event.inputs.filename }}" > training.log 2>&1
        
        # Then run with NSight Compute profiling
        ncu --set full --export ncu_profile "${{ github.event.inputs.filename }}" > ncu.log 2>&1

    - name: Upload training artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: training-artifacts
        path: |
          training.log
          ${{ github.event.inputs.filename }}

    - name: Upload NSight Compute artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ncu-artifacts
        path: |
          ncu.log
          ncu_profile.ncu-rep
      env:
        CUDA_VISIBLE_DEVICES: 0 # Make sure only one GPU is used for testing
